version: '3.8'
services:
  db:
    image: mysql:8.4.4
    container_name: my-mysql
    restart: always
    environment:
#      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - '3306:3306'
    volumes:
      - ms-mysql-volume:/var/lib/mysql
volumes:
  ms-mysql-volume:
    driver: local