server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  retry:
    instances:
      foo-bar:
        max-attempts: 7
        wait-duration: 1s
        enable-exponential-backoff: true
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_APPLICATION_DATASOURCE_URL:jdbc:mysql://localhost:3306/book_service}
    username: ${SPRING_APPLICATION_DATASOURCE_USERNAME:root}
    password: ${SPRING_APPLICATION_DATASOURCE_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    open-in-view: false
    show-sql: false
  management:
    tracing:
      sampling:
        probability: 1.0 # 100%
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
springdoc:
  api-docs:
    path: /book-service/v3/api-docs
  swagger-ui:
    url: /book-service/v3/api-docs
  override-server-url: true
