server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import:
      - optional:configserver:http://localhost:8888
  profiles:
    active:
      - it
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
