server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/josebatista/microservices-erudio-config-server
          search-paths:
            - greeting-service # nome do diretorio no repo